CREATE TABLE CGNAT.COLLECTOR_ALERTS
(
    ID                     VARCHAR2(36 CHAR)              NOT NULL,
    HOSTNAME               VARCHAR2(255 CHAR)             NOT NULL,
    IP                     VARCHAR2(45 CHAR)              NOT NULL,
    FECHA_INICIO           TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    FECHA_FIN              TIMESTAMP(6) WITH TIME ZONE,
    NOMBRE                 VARCHAR2(80 CHAR)              NOT NULL,
    UMBRAL                 NUMBER(9,6)                    NOT NULL,
    PORCENTAJE_INDICADOR   NUMBER(9,6)                    NOT NULL,
    ESTADO                 VARCHAR2(16 CHAR)              NOT NULL,
    FECHA_ENVIO            TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CONSTRAINT PK_COLLECTOR_ALERTS PRIMARY KEY (ID),
    CONSTRAINT CK_COLLECTOR_ALERTS_ESTADO
        CHECK (ESTADO IN ('ACTIVE', 'CLEARED'))
);

CREATE INDEX CGNAT.IX_COLLECTOR_ALERTS_STATE
    ON CGNAT.COLLECTOR_ALERTS (ESTADO, NOMBRE, FECHA_INICIO);

-- Reemplazar CGNAT_ALERT_WRITER por ORACLE_ALERT_USER y ejecutar como owner:
-- GRANT SELECT, INSERT, UPDATE ON CGNAT.COLLECTOR_ALERTS TO CGNAT_ALERT_WRITER;
